---
title: "Module 3 Data 608"
author: "Christina Kasman"
date: "10/6/2019"
output: html_document
---


```{r}
library(readr)  # for read_csv
library(knitr)  # for kable
myfile <- "https://raw.githubusercontent.com/charleyferrari/CUNY_DATA_608/master/module3/data/cleaned-cdc-mortality-1999-2010-2.csv"

Mortality<- read_csv(myfile)
```

```{r}
head(Mortality)
Mortality<-as.data.frame(Mortality)
```


```{r}
library(dplyr)
summary(Mortality)

```
```{r}
unique(Mortality$ICD.Chapter)
```


begin each app with the template
create reactive inputs and outputs
use server function to assemble

Question 1 - For 2010 only, the crude mortality rate across all states from one cause. rank states by crude mortality rate for each cause of death
```{r}
library(ggplot2)
library(shiny)
ui<-fluidPage(titlePanel("Module 3"), 
              selectInput("causeinput","Cause", choices = c( "Certain infectious and parasitic diseases",           "Neoplasms" , "Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism"
 , "Endocrine, nutritional and metabolic diseases"                                                      
 ,"Mental and behavioural disorders"                                                                   
, "Diseases of the nervous system"                                                                     
 , "Diseases of the ear and mastoid process"                                                            
 , "Diseases of the circulatory system"                                                                 
 ,"Diseases of the respiratory system"                                                                 
,"Diseases of the digestive system"                                                                   
, "Diseases of the skin and subcutaneous tissue"                                                       
, "Diseases of the musculoskeletal system and connective tissue"                                       
, "Diseases of the genitourinary system"                                                               
, "Pregnancy, childbirth and the puerperium"                                                           
, "Certain conditions originating in the perinatal period"                                             
, "Congenital malformations, deformations and chromosomal abnormalities"                               
,"Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified"            
, "External causes of morbidity and mortality" ), selected = "Neoplasms"),
  plotOutput(outputId = "hist") 
)

server<-function(input,output){
  output$hist <-renderPlot({
    filtered <-
      Mortality %>%
      filter(ICD.Chapter == input$causeinput,
             Year == "2010"
             )
    ggplot(filtered, aes(x= reorder(State, Crude.Rate), y= Crude.Rate))+
      geom_bar(stat = "identity", fill ="lightblue") +
      ylab("Crude Mortality Rate") +
      xlab("State")+
       coord_flip()
    
    })
}

#shinyApp(ui=ui,server=server)

```
Question 2
```{r}
 
MortalityAgg<- Mortality%>%
  group_by(Year, ICD.Chapter) %>% summarise(Deaths=mean(Deaths), Population =mean(Population))

MortalityAgg$NatAvg<- (MortalityAgg$Deaths / MortalityAgg$Population) *100000

Mortality <- merge(Mortality, MortalityAgg, by=c("Year","ICD.Chapter"), all.x=TRUE)
```

```{r}
ui<-fluidPage(titlePanel("Mortality Rate - State(bars) vs National Average(line)"),
              selectInput("causeinput","Cause", choices = c( "Certain infectious and parasitic diseases",           "Neoplasms" , "Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism"
 , "Endocrine, nutritional and metabolic diseases"                                                      
 ,"Mental and behavioural disorders"                                                                   
, "Diseases of the nervous system"                                                                     
 , "Diseases of the ear and mastoid process"                                                            
 , "Diseases of the circulatory system"                                                                 
 ,"Diseases of the respiratory system"                                                                 
,"Diseases of the digestive system"                                                                   
, "Diseases of the skin and subcutaneous tissue"                                                       
, "Diseases of the musculoskeletal system and connective tissue"                                       
, "Diseases of the genitourinary system"                                                               
, "Pregnancy, childbirth and the puerperium"                                                           
, "Certain conditions originating in the perinatal period"                                             
, "Congenital malformations, deformations and chromosomal abnormalities"                               
,"Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified"            
, "External causes of morbidity and mortality" ), selected = "Neoplasms"),
  plotOutput(outputId = "Q2") ,
selectInput("Stateinput","State",choices=Mortality$State, selected ="NY"),
plotOutput(outputId = "Q2B")
  
)



server<-function(input,output){
  output$Q2 <-renderPlot({
    filtered <-
      Mortality %>%
      filter(ICD.Chapter == input$causeinput,
             State == input$Stateinput
             )
    ggplot(filtered )+
     geom_bar(aes(x=Year, y=Crude.Rate),stat="identity", fill="tan1", colour="sienna3")+
     geom_line(aes(x=Year, y=NatAvg),stat="identity")+
      ylab("Crude Mortality Rate") +
      xlab("Year")
    
    })
}


shinyApp(ui=ui,server=server)

```

